version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aisecurity_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db


  webserver:
    image: nginx:alpine
    container_name: servidornginx_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: app_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./laravel.sql:/docker-entrypoint-initdb.d/laravel.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: admin_pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  db_data:
